<a href="https://colab.research.google.com/github/sheddyranking/Machine-Leanring-Data-Science-Bootcamp.-2022/blob/main/section-2-data-science-and-ml-tools/numpy-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [21]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
#a1.ndim

# Create a 2-dimensional NumPy array using np.array()
a2=  np.array([[1,2,2],[4,5,6]])
#a2.shape

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3.shape

(2, 3, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [22]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.dtype,a1.size,type(a1)

(dtype('int64'), 3, numpy.ndarray)

In [23]:
# Attributes of 2-dimensional array
a2.dtype,a2.size,type(a2)

(dtype('int64'), 6, numpy.ndarray)

In [24]:
# Attributes of 3-dimensional array
a3.dtype,a3.size,type(a3)

(dtype('int64'), 18, numpy.ndarray)

In [28]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame(a2)
data

0  1  2
0  1  2  2
1  4  5  6

In [30]:
# Create an array of shape (10, 2) with only ones

ones = np.ones((10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
# Create an array of shape (7, 2, 3) of only zeros
zeros =np.zeros((7,3,2))
zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [38]:
# Create an array within a range of 0 and 100 with step 3
range= np.arange(0,100,3)
range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [39]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand1= np.random.randint(0,10,size=(7,2))
rand1

array([[4, 4],
       [0, 1],
       [9, 4],
       [2, 0],
       [4, 0],
       [7, 8],
       [8, 4]])

In [44]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand2=np.random.random((3,5))
rand2

array([[0.48740709, 0.67174065, 0.59230378, 0.29211629, 0.23863302],
       [0.20482333, 0.50598582, 0.04607524, 0.73423312, 0.22418   ],
       [0.30640696, 0.04563002, 0.79748706, 0.84708572, 0.93481173]])

In [51]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
rand3 = np.random.randint(10,size=(4,6))
rand3 

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [56]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand4= np.random.randint(1,10,size=(3,7))

# Find the unique numbers in the array you just created
np.unique(rand4)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [58]:
rand4

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6],
       [2, 9, 5, 6, 4, 7, 9]])

In [60]:
# Find the 0'th index of the latest array you created
rand4[0]

array([7, 9, 3, 7, 1, 4, 4])

In [61]:
# Get the first 2 rows of latest array you created
rand4[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [64]:
# Get the first 2 values of the first 2 rows of the latest array
rand4[:2,:2]

array([[7, 9],
       [5, 7]])

In [68]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand5= np.random.randint(10,size=(3,5))
rand6= np.ones((3,5))

#rand6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
# Add the two arrays together
np.add(rand5,rand6)

array([[6., 7., 4., 7., 8.],
       [1., 6., 8., 5., 4.],
       [2., 6., 6., 1., 9.]])

In [112]:
# Create another array of ones of shape (5, 3)
rand7 =  np.ones((5,3))
rand7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [144]:
# Try add the array of ones and the other most recent array together
np.add(rand5,rand7)

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [145]:
## To fix the Error above we need to reshape rand5 to (5,3)

#rand5.shape, rand7.shape
#ouput (3,5), (5,3)

reshape = rand5.reshape(5,3)
#Output (5,3)

#Now try adding them together.

np.add(reshape,rand7)


array([[6., 7., 4.],
       [7., 8., 1.],
       [6., 8., 5.],
       [4., 2., 6.],
       [6., 1., 9.]])

In [143]:
# Create another array of ones of shape (3, 5)
rand8= np.ones((3,5))
rand8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [146]:
# Subtract the new array of ones from the other most recent array
np.subtract(rand5,rand8)

array([[ 4.,  5.,  2.,  5.,  6.],
       [-1.,  4.,  6.,  3.,  2.],
       [ 0.,  4.,  4., -1.,  7.]])

In [147]:
# Multiply the ones array with the latest array
np.multiply(rand5,rand8)

array([[5., 6., 3., 6., 7.],
       [0., 5., 7., 4., 3.],
       [1., 5., 5., 0., 8.]])

In [148]:
# Take the latest array to the power of 2 using '**'
 
rand5**2

array([[25, 36,  9, 36, 49],
       [ 0, 25, 49, 16,  9],
       [ 1, 25, 25,  0, 64]])

In [149]:
# Do the same thing with np.square()
np.square(rand5)

array([[25, 36,  9, 36, 49],
       [ 0, 25, 49, 16,  9],
       [ 1, 25, 25,  0, 64]])

In [150]:
# Find the mean of the latest array using np.mean()
np.mean(rand5)

4.333333333333333

In [151]:
# Find the maximum of the latest array using np.max()
np.max(rand5)

8

In [152]:
# Find the minimum of the latest array using np.min()
np.min(rand5)

0

In [153]:
# Find the standard deviation of the latest array
np.std(rand5)

2.4129281427805145

In [154]:
# Find the variance of the latest array
np.var(rand5)

5.822222222222222

In [155]:
# Reshape the latest array to (3, 5, 1)
rand10 =rand5.reshape(3,5,1)
rand10

array([[[5],
        [6],
        [3],
        [6],
        [7]],

       [[0],
        [5],
        [7],
        [4],
        [3]],

       [[1],
        [5],
        [5],
        [0],
        [8]]])

In [157]:
# Transpose the latest array
rand11 = rand5.T
rand11

array([[5, 0, 1],
       [6, 5, 5],
       [3, 7, 5],
       [6, 4, 0],
       [7, 3, 8]])

What does the transpose do?

In [158]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand12 = np.random.randint(10,size=(3,3))
rand13 = np.random.randint(10,size=(3,2))

In [162]:
# Perform a dot product on the two newest arrays you created
dot1 = np.dot(rand12,rand13)
dot1

array([[67, 33],
       [97, 63],
       [49, 24]])

In [165]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

rand14= np.random.randint(10,size=(4,3))
rand15 = np.random.randint(10,size=(4,3))

In [166]:
# Perform a dot product on the two newest arrays you created
dot2 = np.dot(rand14,rand15)
dot2

ValueError: ignored

It doesn't work. How would you fix it?

In [167]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

dot3 = np.dot(rand14,rand15.T)
dot3

array([[  3,  28,  62,  16],
       [ 25,  36, 120,  34],
       [ 20,  44, 124,  34],
       [ 26,  68, 172,  46]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [168]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand16 = np.random.randint(10,size=(5,3))
rand17= np.random.randint(10,size=(5,3))


In [169]:
# Compare the two arrays with '>'
rand16>rand17

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [170]:
# Compare the two arrays with '>='
rand16>=rand17

array([[ True, False,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False,  True]])

In [172]:
# Find which elements of the first array are greater than 7
rand16>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True]])

In [173]:
# Which parts of each array are equal? (try using '==')
rand16 == rand17

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [176]:
# Sort one of the arrays you just created in ascending order
np.sort(rand16)

array([[3, 5, 7],
       [0, 7, 7],
       [0, 3, 7],
       [3, 5, 7],
       [2, 3, 8]])

In [178]:
rand17

array([[2, 8, 1],
       [1, 1, 5],
       [2, 8, 3],
       [0, 3, 0],
       [4, 3, 7]])

In [177]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand17)

array([[2, 0, 1],
       [0, 1, 2],
       [0, 2, 1],
       [0, 2, 1],
       [1, 0, 2]])

In [180]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand17)

1

In [181]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand17)

9

In [182]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand17,axis=1)

array([1, 2, 1, 1, 2])

In [183]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(rand17,axis=0)

array([4, 0, 4])

In [184]:
# Create an array of normally distributed random numbers
np.random.randn(5,3)

array([[ 0.96337613,  0.41278093,  0.82206016],
       [ 1.89679298, -0.24538812, -0.75373616],
       [-0.88951443, -0.81581028, -0.07710171],
       [ 0.34115197,  0.2766908 ,  0.82718325],
       [ 0.01300189,  1.45353408, -0.26465683]])

In [186]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.