In [107]:
import numpy as np

###  Attributes and Datatypes

In [108]:
### The Main DataType of Numpy is ndarray.

In [109]:
a1 =  np.array([1,2,3])

a1

array([1, 2, 3])

In [110]:
type(al)

numpy.ndarray

In [111]:
a2 =  np.array([[1,2.1,3.0],
                [4.1,5,2.7]])
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [112]:
a3 = np.array([
    [[1,2,3],[2.0,3.0,2],[2,4,5]],
                
     [[1,0,3],[2.0,3.0,7],[2,4,6]]
           ])

a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [113]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [114]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [115]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [116]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [117]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [118]:
import pandas as pd 

In [119]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  4.1  5.0  2.7

   ### Creating arrays from Functions

In [120]:
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
type(ones)

numpy.ndarray

In [122]:
Zeros =  np.zeros((3,5))
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [123]:
type(Zeros)

numpy.ndarray

In [124]:
## start=0, end=0, step=2
array_range = np.arange(0,10,2)

array_range

array([0, 2, 4, 6, 8])

In [125]:
## random numbers between 0&10 with a shape 5,3
rand= np.random.randint(0,10, size=(5,3))
rand

array([[0, 2, 8],
       [9, 6, 4],
       [9, 7, 3],
       [3, 8, 3],
       [0, 1, 0]])

In [126]:
randoms= np.random.random((5,4))

randoms

array([[0.10047397, 0.4826369 , 0.61370347, 0.95124834],
       [0.34875638, 0.27651471, 0.4465059 , 0.95791373],
       [0.17957689, 0.14271575, 0.0835081 , 0.54723513],
       [0.31020924, 0.28271973, 0.92099354, 0.43334216],
       [0.41875723, 0.98622315, 0.79357   , 0.3433051 ]])

In [127]:
#this works almost same as  the Above.

a_rand = np.random.rand(5,4)
a_rand

array([[0.30033908, 0.50395514, 0.62325582, 0.65697232],
       [0.25913577, 0.40519906, 0.66726077, 0.43950131],
       [0.78173551, 0.68462892, 0.73667446, 0.48942286],
       [0.95399141, 0.15373916, 0.64911885, 0.55741353],
       [0.86853158, 0.14362802, 0.44790435, 0.65923332]])

In [128]:
### Pseudo Random Numbers
np.random.seed(0)
#the seed() function prevent a numpy function from generating random numbers once the seed parameter is met so that someone
# can run the same code with generating random numbers

rand_4 = np.random.randint(0,10, (5,4))
rand_4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [129]:
np.random.seed(7) #the rand numbes are static and can be shareavle
a_rand = np.random.rand(5,4)
a_rand

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])

### Viewing Arrays and Metrices 

In [130]:
## this return the Uniques Number from the random Arrays 
np.unique(rand_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
a1

array([1, 2, 3])

In [132]:
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [133]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

#### Selecting a single array within the columns

In [134]:
a1[1]

2

In [135]:
a2[0] # Returns the firt row

array([1. , 2.1, 3. ])

In [136]:
a2[1] # return the second row

array([4.1, 5. , 2.7])

In [137]:
a2[:2,:2] #return the first two values of each row

array([[1. , 2.1],
       [4.1, 5. ]])

In [138]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [141]:
a3[0] # returns the entire first row

array([[1., 2., 3.],
       [2., 3., 2.],
       [2., 4., 5.]])

In [150]:
a3[0,0] #get the second row from the first row above

array([1., 2., 3.])

#### Selecting the Entire Array

In [148]:
a3[:1,:1]  # Selecting the Enter Array to return the first cell

array([[[1., 2., 3.]]])

In [153]:
a3[:2,:2]  # Selecting the Enter Array to return the second cell

array([[[1., 2., 3.],
        [2., 3., 2.]],

       [[1., 0., 3.],
        [2., 3., 7.]]])

In [154]:
a3[:2,:2,:2] ##Select the first Two Rows, and return the first two columns

array([[[1., 2.],
        [2., 3.]],

       [[1., 0.],
        [2., 3.]]])

In [158]:
#2,3,4,5 array, alway count backward to get the dim
rand_5 = np.random.randint(10,size=(2,3,4,5))
rand_5

array([[[[8, 4, 9, 0, 2],
         [0, 7, 6, 2, 9],
         [9, 5, 1, 0, 0],
         [9, 1, 1, 5, 3]],

        [[2, 0, 4, 8, 7],
         [1, 4, 9, 3, 6],
         [7, 1, 0, 2, 7],
         [0, 0, 9, 8, 2]],

        [[0, 5, 5, 0, 9],
         [0, 8, 4, 5, 1],
         [4, 0, 7, 2, 0],
         [3, 9, 8, 3, 7]]],


       [[[1, 0, 1, 4, 6],
         [1, 0, 1, 0, 1],
         [8, 4, 1, 6, 8],
         [5, 2, 4, 7, 4]],

        [[1, 2, 8, 5, 2],
         [9, 6, 2, 5, 7],
         [7, 5, 5, 6, 0],
         [6, 4, 6, 2, 6]],

        [[8, 7, 0, 5, 8],
         [9, 7, 7, 6, 2],
         [5, 6, 1, 9, 3],
         [4, 0, 3, 5, 6]]]])

In [166]:
rand_5[0] #first index metrix(0)

array([[[8, 4, 9, 0, 2],
        [0, 7, 6, 2, 9],
        [9, 5, 1, 0, 0],
        [9, 1, 1, 5, 3]],

       [[2, 0, 4, 8, 7],
        [1, 4, 9, 3, 6],
        [7, 1, 0, 2, 7],
        [0, 0, 9, 8, 2]],

       [[0, 5, 5, 0, 9],
        [0, 8, 4, 5, 1],
        [4, 0, 7, 2, 0],
        [3, 9, 8, 3, 7]]])

In [161]:
rand_5[0,1] ## getting the second metric from the first index metrix(0)

array([[2, 0, 4, 8, 7],
       [1, 4, 9, 3, 6],
       [7, 1, 0, 2, 7],
       [0, 0, 9, 8, 2]])

In [162]:
rand_5[0,2] #getting the third metric from the first index metrix(0)

array([[0, 5, 5, 0, 9],
       [0, 8, 4, 5, 1],
       [4, 0, 7, 2, 0],
       [3, 9, 8, 3, 7]])

In [163]:
rand_5[0,2,2] #getting the third row from the third metrix of the first index metrix(0)

array([4, 0, 7, 2, 0])

In [164]:
rand_5[0,2,:2]  #getting the first 2 row from the third metrix of the first index metrix(0)

array([[0, 5, 5, 0, 9],
       [0, 8, 4, 5, 1]])

In [165]:
rand_5[1] #second index metrix(1)

array([[[1, 0, 1, 4, 6],
        [1, 0, 1, 0, 1],
        [8, 4, 1, 6, 8],
        [5, 2, 4, 7, 4]],

       [[1, 2, 8, 5, 2],
        [9, 6, 2, 5, 7],
        [7, 5, 5, 6, 0],
        [6, 4, 6, 2, 6]],

       [[8, 7, 0, 5, 8],
        [9, 7, 7, 6, 2],
        [5, 6, 1, 9, 3],
        [4, 0, 3, 5, 6]]])

In [168]:
rand_5[1,2,3]  #getting the last row from the third metrix in the second index metix(1)

array([4, 0, 3, 5, 6])

In [172]:
rand_5[1,:3,-1] #select all the columns and return only the last rows

array([[5, 2, 4, 7, 4],
       [6, 4, 6, 2, 6],
       [4, 0, 3, 5, 6]])

In [173]:
rand_5[1,1,1]  #Selecting the second row from the second metrix in the second index metrix(1)

array([9, 6, 2, 5, 7])

In [177]:
rand_5[:,:,:,:4]  ## Getting the first 4-Numbers of the innermost dimensions from all the index

array([[[[8, 4, 9, 0],
         [0, 7, 6, 2],
         [9, 5, 1, 0],
         [9, 1, 1, 5]],

        [[2, 0, 4, 8],
         [1, 4, 9, 3],
         [7, 1, 0, 2],
         [0, 0, 9, 8]],

        [[0, 5, 5, 0],
         [0, 8, 4, 5],
         [4, 0, 7, 2],
         [3, 9, 8, 3]]],


       [[[1, 0, 1, 4],
         [1, 0, 1, 0],
         [8, 4, 1, 6],
         [5, 2, 4, 7]],

        [[1, 2, 8, 5],
         [9, 6, 2, 5],
         [7, 5, 5, 6],
         [6, 4, 6, 2]],

        [[8, 7, 0, 5],
         [9, 7, 7, 6],
         [5, 6, 1, 9],
         [4, 0, 3, 5]]]])

In [178]:
rand_5[:,:,:,:2]  ## Getting the first 2-Numbers of the innermost dimensions from all the metrix

array([[[[8, 4],
         [0, 7],
         [9, 5],
         [9, 1]],

        [[2, 0],
         [1, 4],
         [7, 1],
         [0, 0]],

        [[0, 5],
         [0, 8],
         [4, 0],
         [3, 9]]],


       [[[1, 0],
         [1, 0],
         [8, 4],
         [5, 2]],

        [[1, 2],
         [9, 6],
         [7, 5],
         [6, 4]],

        [[8, 7],
         [9, 7],
         [5, 6],
         [4, 0]]]])