In [6]:
import numpy as np

###  Attributes and Datatypes

In [7]:
### The Main DataType of Numpy is ndarray.

In [8]:
a1 =  np.array([1,2,3])

a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a2 =  np.array([[1,2.1,3.0],
                [4.1,5,2.7]])
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [11]:
a3 = np.array([
    [[1,2,3],[2.0,3.0,2],[2,4,5]],
                
     [[1,0,3],[2.0,3.0,7],[2,4,6]]
           ])

a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
import pandas as pd 

In [18]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  4.1  5.0  2.7

   ### Creating arrays from Functions

In [19]:
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
type(ones)

numpy.ndarray

In [21]:
Zeros =  np.zeros((3,5))
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
type(Zeros)

numpy.ndarray

In [23]:
## start=0, end=0, step=2
array_range = np.arange(0,10,2)

array_range

array([0, 2, 4, 6, 8])

In [24]:
## random numbers between 0&10 with a shape 5,3
rand= np.random.randint(0,10, size=(5,3))
rand

array([[8, 7, 2],
       [5, 1, 9],
       [9, 3, 2],
       [4, 3, 7],
       [6, 3, 2]])

In [25]:
randoms= np.random.random((5,4))

randoms

array([[0.00273962, 0.24564409, 0.96035533, 0.4490123 ],
       [0.67125568, 0.22851656, 0.34241777, 0.88841154],
       [0.05102709, 0.8692993 , 0.90519483, 0.52183872],
       [0.37228094, 0.47652723, 0.20636428, 0.5847181 ],
       [0.25123982, 0.78105566, 0.90999468, 0.19012352]])

In [26]:
#this works almost same as  the Above.

a_rand = np.random.rand(5,4)
a_rand

array([[0.37635316, 0.08136875, 0.81538097, 0.15093889],
       [0.85406948, 0.61908172, 0.40489405, 0.55764871],
       [0.3544971 , 0.14195965, 0.44678913, 0.9339127 ],
       [0.2315338 , 0.8166074 , 0.28631712, 0.43332506],
       [0.27054382, 0.87683815, 0.12074626, 0.50818713]])

In [27]:
### Pseudo Random Numbers
np.random.seed(0)
#the seed() function prevent a numpy function from generating random numbers once the seed parameter is met so that someone
# can run the same code with generating random numbers

rand_4 = np.random.randint(0,10, (5,4))
rand_4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [28]:
np.random.seed(7) #the rand numbes are static and can be shareavle
a_rand = np.random.rand(5,4)
a_rand

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])

### Viewing Arrays and Metrices 

In [29]:
## this return the Uniques Number from the random Arrays 
np.unique(rand_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [32]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

#### Selecting a single array within the columns

In [33]:
a1[1]

2

In [34]:
a2[0] # Returns the firt row

array([1. , 2.1, 3. ])

In [35]:
a2[1] # return the second row

array([4.1, 5. , 2.7])

In [36]:
a2[:2,:2] #return the first two values of each row

array([[1. , 2.1],
       [4.1, 5. ]])

In [37]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [38]:
a3[0] # returns the entire first row

array([[1., 2., 3.],
       [2., 3., 2.],
       [2., 4., 5.]])

In [39]:
a3[0,0] #get the second row from the first row above

array([1., 2., 3.])

In [40]:
a3[0,2,0] # Selecting  the last value from the last row in the first index metrix [0]

2.0

#### Selecting the Entire Array

In [41]:
a3[:1,:1]  # Selecting the Enter Array to return the first cell

array([[[1., 2., 3.]]])

In [42]:
a3[:2,:2]  # Selecting the Enter Array to return the second cell

array([[[1., 2., 3.],
        [2., 3., 2.]],

       [[1., 0., 3.],
        [2., 3., 7.]]])

In [43]:
a3[:2,:2,:2] ##Select the first Two Rows, and return the first two columns

array([[[1., 2.],
        [2., 3.]],

       [[1., 0.],
        [2., 3.]]])

In [44]:
#2,3,4,5 array, alway count backward to get the dim
rand_5 = np.random.randint(10,size=(2,3,4,5))
rand_5

array([[[[0, 2, 8, 9, 6],
         [4, 9, 7, 3, 3],
         [8, 3, 0, 1, 0],
         [0, 6, 7, 7, 9]],

        [[3, 0, 7, 7, 7],
         [0, 5, 4, 3, 1],
         [3, 1, 3, 4, 3],
         [1, 9, 5, 9, 1]],

        [[2, 3, 2, 2, 5],
         [7, 3, 0, 9, 9],
         [3, 4, 5, 3, 0],
         [4, 8, 6, 7, 2]]],


       [[[7, 3, 8, 6, 6],
         [5, 6, 5, 7, 1],
         [5, 4, 4, 9, 9],
         [0, 6, 2, 6, 8]],

        [[2, 4, 1, 6, 1],
         [5, 1, 6, 9, 8],
         [6, 5, 9, 7, 5],
         [4, 9, 6, 8, 1]],

        [[5, 5, 8, 3, 7],
         [7, 9, 4, 7, 5],
         [9, 6, 2, 0, 5],
         [3, 0, 5, 7, 1]]]])

In [45]:
rand_5[0] #first index metrix(0)

array([[[0, 2, 8, 9, 6],
        [4, 9, 7, 3, 3],
        [8, 3, 0, 1, 0],
        [0, 6, 7, 7, 9]],

       [[3, 0, 7, 7, 7],
        [0, 5, 4, 3, 1],
        [3, 1, 3, 4, 3],
        [1, 9, 5, 9, 1]],

       [[2, 3, 2, 2, 5],
        [7, 3, 0, 9, 9],
        [3, 4, 5, 3, 0],
        [4, 8, 6, 7, 2]]])

In [46]:
rand_5[0,1] ## getting the second metric from the first index metrix(0)

array([[3, 0, 7, 7, 7],
       [0, 5, 4, 3, 1],
       [3, 1, 3, 4, 3],
       [1, 9, 5, 9, 1]])

In [47]:
rand_5[0,2] #getting the third metric from the first index metrix(0)

array([[2, 3, 2, 2, 5],
       [7, 3, 0, 9, 9],
       [3, 4, 5, 3, 0],
       [4, 8, 6, 7, 2]])

In [48]:
rand_5[0,2,2] #getting the third row from the third metrix of the first index metrix(0)

array([3, 4, 5, 3, 0])

In [49]:
rand_5[0,2,:2]  #getting the first 2 row from the third metrix of the first index metrix(0)

array([[2, 3, 2, 2, 5],
       [7, 3, 0, 9, 9]])

In [50]:
rand_5[1] #second index metrix(1)

array([[[7, 3, 8, 6, 6],
        [5, 6, 5, 7, 1],
        [5, 4, 4, 9, 9],
        [0, 6, 2, 6, 8]],

       [[2, 4, 1, 6, 1],
        [5, 1, 6, 9, 8],
        [6, 5, 9, 7, 5],
        [4, 9, 6, 8, 1]],

       [[5, 5, 8, 3, 7],
        [7, 9, 4, 7, 5],
        [9, 6, 2, 0, 5],
        [3, 0, 5, 7, 1]]])

In [51]:
rand_5[1,2,3]  #getting the last row from the third metrix in the second index metix(1)

array([3, 0, 5, 7, 1])

In [52]:
rand_5[1,:3,-1] #select all the columns and return only the last rows

array([[0, 6, 2, 6, 8],
       [4, 9, 6, 8, 1],
       [3, 0, 5, 7, 1]])

In [53]:
rand_5[1,1,1]  #Selecting the second row from the second metrix in the second index metrix(1)

array([5, 1, 6, 9, 8])

In [54]:
rand_5[:,:,:,:4]  ## Getting the first 4-Numbers of the innermost dimensions from all the index

array([[[[0, 2, 8, 9],
         [4, 9, 7, 3],
         [8, 3, 0, 1],
         [0, 6, 7, 7]],

        [[3, 0, 7, 7],
         [0, 5, 4, 3],
         [3, 1, 3, 4],
         [1, 9, 5, 9]],

        [[2, 3, 2, 2],
         [7, 3, 0, 9],
         [3, 4, 5, 3],
         [4, 8, 6, 7]]],


       [[[7, 3, 8, 6],
         [5, 6, 5, 7],
         [5, 4, 4, 9],
         [0, 6, 2, 6]],

        [[2, 4, 1, 6],
         [5, 1, 6, 9],
         [6, 5, 9, 7],
         [4, 9, 6, 8]],

        [[5, 5, 8, 3],
         [7, 9, 4, 7],
         [9, 6, 2, 0],
         [3, 0, 5, 7]]]])

In [55]:
rand_5[:,:,:,:2]  ## Getting the first 2-column of the innermost dimensions from all the metrix

array([[[[0, 2],
         [4, 9],
         [8, 3],
         [0, 6]],

        [[3, 0],
         [0, 5],
         [3, 1],
         [1, 9]],

        [[2, 3],
         [7, 3],
         [3, 4],
         [4, 8]]],


       [[[7, 3],
         [5, 6],
         [5, 4],
         [0, 6]],

        [[2, 4],
         [5, 1],
         [6, 5],
         [4, 9]],

        [[5, 5],
         [7, 9],
         [9, 6],
         [3, 0]]]])

In [56]:
rand_5

array([[[[0, 2, 8, 9, 6],
         [4, 9, 7, 3, 3],
         [8, 3, 0, 1, 0],
         [0, 6, 7, 7, 9]],

        [[3, 0, 7, 7, 7],
         [0, 5, 4, 3, 1],
         [3, 1, 3, 4, 3],
         [1, 9, 5, 9, 1]],

        [[2, 3, 2, 2, 5],
         [7, 3, 0, 9, 9],
         [3, 4, 5, 3, 0],
         [4, 8, 6, 7, 2]]],


       [[[7, 3, 8, 6, 6],
         [5, 6, 5, 7, 1],
         [5, 4, 4, 9, 9],
         [0, 6, 2, 6, 8]],

        [[2, 4, 1, 6, 1],
         [5, 1, 6, 9, 8],
         [6, 5, 9, 7, 5],
         [4, 9, 6, 8, 1]],

        [[5, 5, 8, 3, 7],
         [7, 9, 4, 7, 5],
         [9, 6, 2, 0, 5],
         [3, 0, 5, 7, 1]]]])

In [57]:
rand_5[1,2] #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [58]:
rand_5[1,2,3,0] ## Selecting the last value from the third metrix in the second index metrix [1]

3

In [59]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [60]:
rand_5[1,2,:,:2] ## Selecting the first two columns from the third metrix in the second index metrix [1]

array([[5, 5],
       [7, 9],
       [9, 6],
       [3, 0]])

In [61]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [62]:
rand_5[1, 2, 2:4,:2] #slicing the 2nd,3rd row & 1st,2nd Column, from the third metrix in the second index metrix [1]

array([[9, 6],
       [3, 0]])

In [63]:
rand_5[1,2]  #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [64]:
rand_5[1,2,2:4,1:3] #slicing the 2nd,3rd row & 2nd,3rd Column, from the third metrix in the second index metrix [1]

array([[6, 2],
       [0, 5]])

In [65]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [66]:
rand_5[1,2,2:4,3:5]  #slicing the 2nd,3rd row & 4th,5th Column, from the third metrix in the second index metrix [1]

array([[0, 5],
       [7, 1]])


### Manipulation of Arrays

Arithemetics

In [67]:
a1

array([1, 2, 3])

In [68]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [70]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [71]:
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [72]:
a1

array([1, 2, 3])

In [73]:
a1*a2

array([[ 1. ,  4.2,  9. ],
       [ 4.1, 10. ,  8.1]])

In [74]:
a1/a2

array([[1.        , 0.95238095, 1.        ],
       [0.24390244, 0.4       , 1.11111111]])

In [75]:
a1%a2

array([[0. , 2. , 0. ],
       [1. , 2. , 0.3]])

In [76]:
a2/2

array([[0.5 , 1.05, 1.5 ],
       [2.05, 2.5 , 1.35]])

In [77]:
a2%2 #remainder

array([[1. , 0.1, 1. ],
       [0.1, 1. , 0.7]])

In [78]:
np.add(a1,a2) #function can be used as well 

array([[2. , 4.1, 6. ],
       [5.1, 7. , 5.7]])

In [79]:
a2**2 

array([[ 1.  ,  4.41,  9.  ],
       [16.81, 25.  ,  7.29]])

In [80]:
np.square(a2)  # this does same above

array([[ 1.  ,  4.41,  9.  ],
       [16.81, 25.  ,  7.29]])

In [81]:
np.exp(a2) #exponetial

array([[  2.71828183,   8.16616991,  20.08553692],
       [ 60.3402876 , 148.4131591 ,  14.87973172]])

In [82]:
a2//a3

##this dosent work google solution. with ValueError below Or use StackOverflow.

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [84]:
np.log(a3)

C:\Users\sheddyranking\AppData\Local\Temp\ipykernel_13868\1844188880.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a3)


array([[[0.        , 0.69314718, 1.09861229],
        [0.69314718, 1.09861229, 0.69314718],
        [0.69314718, 1.38629436, 1.60943791]],

       [[0.        ,       -inf, 1.09861229],
        [0.69314718, 1.09861229, 1.94591015],
        [0.69314718, 1.38629436, 1.79175947]]])

### Aggregation

Use `Sum()` on Python DataTypes and `np.sum()` on Numpy DataTypes
See Exampel below.

In [94]:
#Python datatypes
listy_list = [1,2,3]
type(listy_list)

list

In [96]:
sum(listy_list)

6

In [91]:
a1

array([1, 2, 3])

In [92]:
type(a1)

numpy.ndarray

In [97]:
np.sum(a1)

6

####  Both the Python and Numpy Datatype return the result but there excecution time diffirers. let's creat a Massive 
#### array below and see and example.

In [98]:
massive_a= np.random.random(10000)

type(massive_a)

numpy.ndarray

In [100]:
massive_a[:10] # view first 10

array([0.79808141, 0.54427185, 0.41841659, 0.01915666, 0.68377373,
       0.48809792, 0.22057967, 0.55054305, 0.52259111, 0.48755248])

In [102]:
# Check the execution

%timeit sum(massive_a) ## Python list
%timeit np.sum(massive_a) ## Numpy 

# Results shows that Numpy runs faster

1.87 ms ± 98.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
20.5 µs ± 2.36 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [103]:
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [105]:
a2.mean()

2.983333333333333

In [106]:
a2.var()

1.6847222222222218

In [107]:
a2.std()

1.2979684981625024

In [108]:
np.sqrt(a2.var()) #Std is the sqrt of variance. 

1.2979684981625024