In [9]:
import numpy as np

###  Attributes and Datatypes

In [10]:
### The Main DataType of Numpy is ndarray.

In [11]:
a1 =  np.array([1,2,3])

a1

array([1, 2, 3])

In [12]:
type(al)

numpy.ndarray

In [13]:
a2 =  np.array([[1,2.1,3.0],
                [4.1,5,2.7]])
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [14]:
a3 = np.array([
    [[1,2,3],[2.0,3.0,2],[2,4,5]],
                
     [[1,2,3],[2.0,3.0,2],[2,4,5]]
           ])

a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]]])

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [17]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
import pandas as pd 

In [23]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  4.1  5.0  2.7