In [9]:
import numpy as np

###  Attributes and Datatypes

In [10]:
### The Main DataType of Numpy is ndarray.

In [11]:
a1 =  np.array([1,2,3])

a1

array([1, 2, 3])

In [12]:
type(al)

numpy.ndarray

In [13]:
a2 =  np.array([[1,2.1,3.0],
                [4.1,5,2.7]])
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [14]:
a3 = np.array([
    [[1,2,3],[2.0,3.0,2],[2,4,5]],
                
     [[1,2,3],[2.0,3.0,2],[2,4,5]]
           ])

a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]]])

In [15]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [16]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [17]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [18]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
import pandas as pd 

In [23]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  4.1  5.0  2.7

   ### Creating arrays from Functions

In [26]:
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
type(ones)

numpy.ndarray

In [34]:
Zeros =  np.zeros((3,5))
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
type(Zeros)

numpy.ndarray

In [38]:
## start=0, end=0, step=2
array_range = np.arange(0,10,2)

array_range

array([0, 2, 4, 6, 8])

In [41]:
## random numbers between 0&10 with a shape 5,3
rand= np.random.randint(0,10, size=(5,3))
rand

array([[3, 8, 4],
       [4, 9, 6],
       [7, 7, 1],
       [4, 3, 2],
       [2, 3, 2]])

In [56]:
randoms= np.random.random((5,4))

randoms

array([[0.23284846, 0.93783534, 0.42363406, 0.44226121],
       [0.14087883, 0.47340849, 0.73383677, 0.83956206],
       [0.08192469, 0.16074449, 0.45771658, 0.94998672],
       [0.41716851, 0.88232344, 0.77525687, 0.79263823],
       [0.77960031, 0.78721268, 0.83536728, 0.81611361]])

In [59]:
#this works almost same as  the Above.

a_rand = np.random.rand(5,4)
a_rand

array([[0.16655433, 0.21295342, 0.74245909, 0.99772659],
       [0.04211353, 0.70568053, 0.77018027, 0.01086056],
       [0.10569683, 0.72626069, 0.4677933 , 0.56090308],
       [0.27064775, 0.66145913, 0.35751338, 0.39807774],
       [0.07895668, 0.75138644, 0.52143318, 0.60388329]])

In [69]:
### Pseudo Random Numbers
np.random.seed(0)
#the seed() function prevent a numpy function from generating random numbers once the seed parameter is met so that someone
# can run the same code with generating random numbers

rand_4 = np.random.randint(0,10, (5,4))
rand_4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [73]:
np.random.seed(7) #the rand numbes are static and can be shareavle
a_rand = np.random.rand(5,4)
a_rand

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])