In [179]:
import numpy as np

###  Attributes and Datatypes

In [180]:
### The Main DataType of Numpy is ndarray.

In [181]:
a1 =  np.array([1,2,3])

a1

array([1, 2, 3])

In [182]:
type(al)

numpy.ndarray

In [183]:
a2 =  np.array([[1,2.1,3.0],
                [4.1,5,2.7]])
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [184]:
a3 = np.array([
    [[1,2,3],[2.0,3.0,2],[2,4,5]],
                
     [[1,0,3],[2.0,3.0,7],[2,4,6]]
           ])

a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [185]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [186]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [187]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [188]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('float64'))

In [189]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [190]:
import pandas as pd 

In [191]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.1  3.0
1  4.1  5.0  2.7

   ### Creating arrays from Functions

In [192]:
ones = np.ones((5,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [193]:
type(ones)

numpy.ndarray

In [194]:
Zeros =  np.zeros((3,5))
Zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [195]:
type(Zeros)

numpy.ndarray

In [196]:
## start=0, end=0, step=2
array_range = np.arange(0,10,2)

array_range

array([0, 2, 4, 6, 8])

In [197]:
## random numbers between 0&10 with a shape 5,3
rand= np.random.randint(0,10, size=(5,3))
rand

array([[4, 0, 4],
       [1, 5, 2],
       [4, 8, 7],
       [5, 7, 5],
       [3, 7, 6]])

In [198]:
randoms= np.random.random((5,4))

randoms

array([[0.56505187, 0.3038221 , 0.48092528, 0.3150298 ],
       [0.03802221, 0.56894916, 0.98576413, 0.37323235],
       [0.67976854, 0.12209437, 0.09265119, 0.63295346],
       [0.28088024, 0.27140348, 0.89021819, 0.20350881],
       [0.29111026, 0.54722999, 0.71629064, 0.51835422]])

In [199]:
#this works almost same as  the Above.

a_rand = np.random.rand(5,4)
a_rand

array([[0.7335823 , 0.05897287, 0.58623112, 0.58279402],
       [0.6280577 , 0.71518211, 0.24324772, 0.72598572],
       [0.97045799, 0.37776588, 0.16968004, 0.3548634 ],
       [0.60486355, 0.56297084, 0.62413032, 0.69169301],
       [0.43177954, 0.1799175 , 0.61705049, 0.42296652]])

In [200]:
### Pseudo Random Numbers
np.random.seed(0)
#the seed() function prevent a numpy function from generating random numbers once the seed parameter is met so that someone
# can run the same code with generating random numbers

rand_4 = np.random.randint(0,10, (5,4))
rand_4

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [201]:
np.random.seed(7) #the rand numbes are static and can be shareavle
a_rand = np.random.rand(5,4)
a_rand

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])

### Viewing Arrays and Metrices 

In [202]:
## this return the Uniques Number from the random Arrays 
np.unique(rand_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
a1

array([1, 2, 3])

In [204]:
a2

array([[1. , 2.1, 3. ],
       [4.1, 5. , 2.7]])

In [205]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

#### Selecting a single array within the columns

In [206]:
a1[1]

2

In [207]:
a2[0] # Returns the firt row

array([1. , 2.1, 3. ])

In [208]:
a2[1] # return the second row

array([4.1, 5. , 2.7])

In [209]:
a2[:2,:2] #return the first two values of each row

array([[1. , 2.1],
       [4.1, 5. ]])

In [210]:
a3

array([[[1., 2., 3.],
        [2., 3., 2.],
        [2., 4., 5.]],

       [[1., 0., 3.],
        [2., 3., 7.],
        [2., 4., 6.]]])

In [211]:
a3[0] # returns the entire first row

array([[1., 2., 3.],
       [2., 3., 2.],
       [2., 4., 5.]])

In [212]:
a3[0,0] #get the second row from the first row above

array([1., 2., 3.])

In [236]:
a3[0,2,0] # Selecting  the last value from the last row in the first index metrix [0]

2.0

#### Selecting the Entire Array

In [213]:
a3[:1,:1]  # Selecting the Enter Array to return the first cell

array([[[1., 2., 3.]]])

In [214]:
a3[:2,:2]  # Selecting the Enter Array to return the second cell

array([[[1., 2., 3.],
        [2., 3., 2.]],

       [[1., 0., 3.],
        [2., 3., 7.]]])

In [215]:
a3[:2,:2,:2] ##Select the first Two Rows, and return the first two columns

array([[[1., 2.],
        [2., 3.]],

       [[1., 0.],
        [2., 3.]]])

In [216]:
#2,3,4,5 array, alway count backward to get the dim
rand_5 = np.random.randint(10,size=(2,3,4,5))
rand_5

array([[[[0, 2, 8, 9, 6],
         [4, 9, 7, 3, 3],
         [8, 3, 0, 1, 0],
         [0, 6, 7, 7, 9]],

        [[3, 0, 7, 7, 7],
         [0, 5, 4, 3, 1],
         [3, 1, 3, 4, 3],
         [1, 9, 5, 9, 1]],

        [[2, 3, 2, 2, 5],
         [7, 3, 0, 9, 9],
         [3, 4, 5, 3, 0],
         [4, 8, 6, 7, 2]]],


       [[[7, 3, 8, 6, 6],
         [5, 6, 5, 7, 1],
         [5, 4, 4, 9, 9],
         [0, 6, 2, 6, 8]],

        [[2, 4, 1, 6, 1],
         [5, 1, 6, 9, 8],
         [6, 5, 9, 7, 5],
         [4, 9, 6, 8, 1]],

        [[5, 5, 8, 3, 7],
         [7, 9, 4, 7, 5],
         [9, 6, 2, 0, 5],
         [3, 0, 5, 7, 1]]]])

In [217]:
rand_5[0] #first index metrix(0)

array([[[0, 2, 8, 9, 6],
        [4, 9, 7, 3, 3],
        [8, 3, 0, 1, 0],
        [0, 6, 7, 7, 9]],

       [[3, 0, 7, 7, 7],
        [0, 5, 4, 3, 1],
        [3, 1, 3, 4, 3],
        [1, 9, 5, 9, 1]],

       [[2, 3, 2, 2, 5],
        [7, 3, 0, 9, 9],
        [3, 4, 5, 3, 0],
        [4, 8, 6, 7, 2]]])

In [218]:
rand_5[0,1] ## getting the second metric from the first index metrix(0)

array([[3, 0, 7, 7, 7],
       [0, 5, 4, 3, 1],
       [3, 1, 3, 4, 3],
       [1, 9, 5, 9, 1]])

In [219]:
rand_5[0,2] #getting the third metric from the first index metrix(0)

array([[2, 3, 2, 2, 5],
       [7, 3, 0, 9, 9],
       [3, 4, 5, 3, 0],
       [4, 8, 6, 7, 2]])

In [220]:
rand_5[0,2,2] #getting the third row from the third metrix of the first index metrix(0)

array([3, 4, 5, 3, 0])

In [221]:
rand_5[0,2,:2]  #getting the first 2 row from the third metrix of the first index metrix(0)

array([[2, 3, 2, 2, 5],
       [7, 3, 0, 9, 9]])

In [222]:
rand_5[1] #second index metrix(1)

array([[[7, 3, 8, 6, 6],
        [5, 6, 5, 7, 1],
        [5, 4, 4, 9, 9],
        [0, 6, 2, 6, 8]],

       [[2, 4, 1, 6, 1],
        [5, 1, 6, 9, 8],
        [6, 5, 9, 7, 5],
        [4, 9, 6, 8, 1]],

       [[5, 5, 8, 3, 7],
        [7, 9, 4, 7, 5],
        [9, 6, 2, 0, 5],
        [3, 0, 5, 7, 1]]])

In [223]:
rand_5[1,2,3]  #getting the last row from the third metrix in the second index metix(1)

array([3, 0, 5, 7, 1])

In [224]:
rand_5[1,:3,-1] #select all the columns and return only the last rows

array([[0, 6, 2, 6, 8],
       [4, 9, 6, 8, 1],
       [3, 0, 5, 7, 1]])

In [225]:
rand_5[1,1,1]  #Selecting the second row from the second metrix in the second index metrix(1)

array([5, 1, 6, 9, 8])

In [226]:
rand_5[:,:,:,:4]  ## Getting the first 4-Numbers of the innermost dimensions from all the index

array([[[[0, 2, 8, 9],
         [4, 9, 7, 3],
         [8, 3, 0, 1],
         [0, 6, 7, 7]],

        [[3, 0, 7, 7],
         [0, 5, 4, 3],
         [3, 1, 3, 4],
         [1, 9, 5, 9]],

        [[2, 3, 2, 2],
         [7, 3, 0, 9],
         [3, 4, 5, 3],
         [4, 8, 6, 7]]],


       [[[7, 3, 8, 6],
         [5, 6, 5, 7],
         [5, 4, 4, 9],
         [0, 6, 2, 6]],

        [[2, 4, 1, 6],
         [5, 1, 6, 9],
         [6, 5, 9, 7],
         [4, 9, 6, 8]],

        [[5, 5, 8, 3],
         [7, 9, 4, 7],
         [9, 6, 2, 0],
         [3, 0, 5, 7]]]])

In [227]:
rand_5[:,:,:,:2]  ## Getting the first 2-Numbers of the innermost dimensions from all the metrix

array([[[[0, 2],
         [4, 9],
         [8, 3],
         [0, 6]],

        [[3, 0],
         [0, 5],
         [3, 1],
         [1, 9]],

        [[2, 3],
         [7, 3],
         [3, 4],
         [4, 8]]],


       [[[7, 3],
         [5, 6],
         [5, 4],
         [0, 6]],

        [[2, 4],
         [5, 1],
         [6, 5],
         [4, 9]],

        [[5, 5],
         [7, 9],
         [9, 6],
         [3, 0]]]])

In [230]:
rand_5

array([[[[0, 2, 8, 9, 6],
         [4, 9, 7, 3, 3],
         [8, 3, 0, 1, 0],
         [0, 6, 7, 7, 9]],

        [[3, 0, 7, 7, 7],
         [0, 5, 4, 3, 1],
         [3, 1, 3, 4, 3],
         [1, 9, 5, 9, 1]],

        [[2, 3, 2, 2, 5],
         [7, 3, 0, 9, 9],
         [3, 4, 5, 3, 0],
         [4, 8, 6, 7, 2]]],


       [[[7, 3, 8, 6, 6],
         [5, 6, 5, 7, 1],
         [5, 4, 4, 9, 9],
         [0, 6, 2, 6, 8]],

        [[2, 4, 1, 6, 1],
         [5, 1, 6, 9, 8],
         [6, 5, 9, 7, 5],
         [4, 9, 6, 8, 1]],

        [[5, 5, 8, 3, 7],
         [7, 9, 4, 7, 5],
         [9, 6, 2, 0, 5],
         [3, 0, 5, 7, 1]]]])

In [298]:
rand_5[1,2] #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [238]:
rand_5[1,2,3,0] ## Selecting the last value from the third metrix in the second index metrix [1]

3

In [299]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [279]:
rand_5[1,2,:,:2] ## Selecting the first two columns from the third metrix in the second index metrix [1]

array([[5, 5],
       [7, 9],
       [9, 6],
       [3, 0]])

In [300]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [286]:
rand_5[1, 2, 2:4,:2] #slicing the 2nd,3rd row & 1st,2nd Column, from the third metrix in the second index metrix [1]

array([[9, 6],
       [3, 0]])

In [301]:
rand_5[1,2]  #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [307]:
rand_5[1,2,2:4,1:3] #slicing the 2nd,3rd row & 2nd,3rd Column, from the third metrix in the second index metrix [1]

array([[6, 2],
       [0, 5]])

In [304]:
rand_5[1,2]   #third metrix in the second index metrix [1]

array([[5, 5, 8, 3, 7],
       [7, 9, 4, 7, 5],
       [9, 6, 2, 0, 5],
       [3, 0, 5, 7, 1]])

In [297]:
rand_5[1,2,2:4,3:5]  #slicing the 2nd,3rd row & 4th,5th Column, from the third metrix in the second index metrix [1]

array([[0, 5],
       [7, 1]])